-- Production tickets generated by POS orders and consumed by KDS.
-- Apply after 008_pos_products.sql.

create table if not exists public.production_tickets (
  id uuid primary key default gen_random_uuid(),
  order_id text not null,
  table_id text,
  table_name text not null,
  area_id text not null references public.areas(id),
  area_name text not null,
  waiter_id uuid references public.profiles(id),
  waiter_name text,
  status text not null default 'pending'
    check (status in ('pending', 'in_production', 'ready', 'served', 'problem', 'cancelled')),
  priority text not null default 'normal'
    check (priority in ('low', 'normal', 'high', 'urgent')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  started_at timestamptz,
  ready_at timestamptz,
  served_at timestamptz
);

create table if not exists public.production_ticket_items (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.production_tickets(id) on delete cascade,
  order_item_id text not null,
  product_id uuid not null references public.pos_products(id),
  product_name text not null,
  quantity numeric not null default 1 check (quantity > 0),
  notes text,
  modifiers jsonb not null default '[]'::jsonb,
  status text not null default 'pending'
    check (status in ('pending', 'in_production', 'ready', 'served', 'problem', 'cancelled')),
  created_at timestamptz not null default now()
);

create index if not exists production_tickets_area_status_created_idx
  on public.production_tickets (area_id, status, created_at desc);
create index if not exists production_ticket_items_ticket_idx
  on public.production_ticket_items (ticket_id);
create unique index if not exists production_ticket_order_item_unique_idx
  on public.production_ticket_items (order_item_id);

alter table public.production_tickets enable row level security;
alter table public.production_ticket_items enable row level security;

grant select, insert, update on public.production_tickets to authenticated;
grant select, insert, update on public.production_ticket_items to authenticated;
grant all on public.production_tickets, public.production_ticket_items to service_role;

create or replace function public.can_operate_production_tickets()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and status = 'active'
      and role in (
        'admin', 'gerente_general', 'supervisor', 'mesero', 'cajero',
        'cocinero', 'pizzero', 'barista', 'bartender', 'repostero', 'panadero'
      )
  );
$$;

revoke all on function public.can_operate_production_tickets() from public;
grant execute on function public.can_operate_production_tickets() to authenticated;

drop policy if exists "production_tickets_authenticated_read" on public.production_tickets;
create policy "production_tickets_authenticated_read"
  on public.production_tickets for select to authenticated
  using (true);

drop policy if exists "production_ticket_items_authenticated_read" on public.production_ticket_items;
create policy "production_ticket_items_authenticated_read"
  on public.production_ticket_items for select to authenticated
  using (true);

drop policy if exists "production_tickets_operators_update" on public.production_tickets;
create policy "production_tickets_operators_update"
  on public.production_tickets for update to authenticated
  using (public.can_operate_production_tickets())
  with check (public.can_operate_production_tickets());

drop policy if exists "production_ticket_items_operators_update" on public.production_ticket_items;
create policy "production_ticket_items_operators_update"
  on public.production_ticket_items for update to authenticated
  using (public.can_operate_production_tickets())
  with check (public.can_operate_production_tickets());

create or replace function public.set_production_ticket_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists set_production_ticket_updated_at on public.production_tickets;
create trigger set_production_ticket_updated_at
  before update on public.production_tickets
  for each row execute procedure public.set_production_ticket_updated_at();

create or replace function public.create_production_tickets_from_order(
  p_order jsonb,
  p_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  item_data jsonb;
  product public.pos_products;
  production_area public.areas;
  area_row record;
  ticket public.production_tickets;
  ticket_ids uuid[] := '{}'::uuid[];
  product_id_text text;
  item_area_id text;
  item_quantity numeric;
begin
  if not public.can_operate_production_tickets() then
    raise exception 'No tienes permiso para enviar comandas.';
  end if;
  if nullif(trim(p_order ->> 'order_id'), '') is null then
    raise exception 'La orden no tiene identificador.';
  end if;
  if jsonb_array_length(coalesce(p_items, '[]'::jsonb)) = 0 then
    raise exception 'No hay productos nuevos para enviar.';
  end if;

  for item_data in select value from jsonb_array_elements(p_items)
  loop
    product_id_text := nullif(trim(item_data ->> 'product_id'), '');
    item_area_id := nullif(trim(item_data ->> 'production_area_id'), '');
    item_quantity := coalesce((item_data ->> 'quantity')::numeric, 0);
    if product_id_text is null or item_area_id is null or item_quantity <= 0 then
      raise exception 'Una linea de la orden no tiene producto, area o cantidad valida.';
    end if;
    select * into product
    from public.pos_products
    where id::text = product_id_text
      and active = true
      and production_ready = true;
    if product.id is null then
      raise exception 'Producto POS no listo para produccion: %.', coalesce(item_data ->> 'product_name', product_id_text);
    end if;
    if product.recipe_id is null or product.production_area_id is distinct from item_area_id then
      raise exception 'Producto % no tiene receta o area de produccion valida.', product.name;
    end if;
  end loop;

  for area_row in
    select distinct trim(value ->> 'production_area_id') as area_id
    from jsonb_array_elements(p_items)
  loop
    select * into production_area
    from public.areas
    where id = area_row.area_id
      and active = true
      and is_production_area = true;
    if production_area.id is null then
      raise exception 'El area de produccion % no esta activa.', area_row.area_id;
    end if;

    insert into public.production_tickets (
      order_id, table_id, table_name, area_id, area_name, waiter_id,
      waiter_name, status, priority, notes
    ) values (
      trim(p_order ->> 'order_id'),
      nullif(trim(p_order ->> 'table_id'), ''),
      coalesce(nullif(trim(p_order ->> 'table_name'), ''), 'Orden POS'),
      production_area.id,
      production_area.name,
      auth.uid(),
      nullif(trim(p_order ->> 'waiter_name'), ''),
      'pending',
      coalesce(nullif(trim(p_order ->> 'priority'), ''), 'normal'),
      nullif(trim(p_order ->> 'notes'), '')
    ) returning * into ticket;
    ticket_ids := array_append(ticket_ids, ticket.id);

    for item_data in
      select value from jsonb_array_elements(p_items)
      where trim(value ->> 'production_area_id') = area_row.area_id
    loop
      select * into product
      from public.pos_products
      where id::text = trim(item_data ->> 'product_id');
      insert into public.production_ticket_items (
        ticket_id, order_item_id, product_id, product_name, quantity,
        notes, modifiers, status
      ) values (
        ticket.id,
        trim(item_data ->> 'order_item_id'),
        product.id,
        product.name,
        (item_data ->> 'quantity')::numeric,
        nullif(trim(item_data ->> 'notes'), ''),
        coalesce(item_data -> 'modifiers', '[]'::jsonb),
        'pending'
      );
    end loop;
  end loop;

  return jsonb_build_object('ticket_ids', to_jsonb(ticket_ids));
end;
$$;

revoke all on function public.create_production_tickets_from_order(jsonb, jsonb) from public;
grant execute on function public.create_production_tickets_from_order(jsonb, jsonb) to authenticated;
